Performing Course Work for Course 1 Practical Test
EugeneParallax/CourseWork1 pull request #1
Opened 2023-12-10 16:24 UTC by EugeneParallax

2023-12-11 09:43 UTC, safgbad requested changes

2023-12-11 09:43 UTC, safgbad commented on src/Employee.java
> +        employee.employeeID = employeeIDCounter;
это, конечно, работает, но это не конструктор

конструктор не является статическим, он не должен ничего возвращать
оформляется он так:
```java
[модификатор доступа] [название класса] ([параметры через запятую]) {
    // ...
}
```
перепиши, пожалуйста

2023-12-11 09:43 UTC, safgbad commented on src/Employee.java
> +        employee.branch = (byte) branch;
почему бы в таком случае сразу не принимать параметр типа byte?
или наоборот – поменять тип поля branch на int

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        }
круто, что проводишь валидацию номера отдела &#128077;

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +                    if (s < length) {
интересная реализация, однако в коде теряется преимущество того, что все null-значения в массиве идут в конце

под этим имею в виду логику добавления
если мы знаем, что добавляется всегда в конец, то имеет смысл хранить число сотрудников и в методе addEmployee добавлять сразу в конец, а не проходить в цикле по всему массиву:
```java
private int counter;

public void addEmployee(String lastName, String firstName, String patronymic, int branch, int salary) {
    if (counter >= employeeList.length) {
        throw new RuntimeException("Невозможно добавить нового сотрудника - книга заполнена");
    }
    if (branch < 1 || branch > branchNumber) {
        throw new RuntimeException("Номер отдела нового сотрудника задан неверно");
    }
    employeeList[counter++] = new Employee(lastName, firstName, patronymic, branch, salary);
}
```
ну и при удалении нужно будет у counter отнять 1

вообще ТЗ не подразумевает, что null должны быть в конце
но код рабочий, так что можно оставить как есть
это просто информация "на подумать")

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
тут в условии либо <=, либо -1 нужно убрать
цикл не доходит до последнего элемента

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
интересно придумал с отделами
я бы еще предложил сделать для каждого из методов, связанных с отделами, по перегрузке без параметров таким образом:
```java
public int findSalaryTotal() {
    return findSalaryTotal(0);
}
```
просто не сразу очевидно, что нужно ввести 0 как параметр

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        return salaryTotal / members;
вычисление среднего зачастую предполагает, что ответ не будет целым
по-хорошему метод должен возвращать double, а в return'е следует сделать приведение типов:
```java
return (double) salaryTotal / members;
```

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        int salaryMinEmployee = 0;
если 0-й сотрудник не будет в нужном отделе, то есть большая вероятность, что результат работы метода будет неверным

здесь нужно инициализировать таки образом:
```java
int salaryMin = Integer.MAX_VALUE;
int salaryMinEmployee = -1;
```
в цикле нужно идти по всем элементам с нулевого до последнего. обрати внимание – здесь верхняя граница в условии также прописана неверно
также в конце метода следует проверить salaryMinEmployee на -1. если -1, то в отделе никто не работает и следует возвращать null
то же самое касается и нахождения максимума

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length - 1; i++) {
границы указаны неверно

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length - 1; i++) {
границы указаны неверно

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 0; i < length; i++) {
границы указаны неверно

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        String keyword = lastName + ' ' + firstName + ' ' + patronymic;
по-хорошему проверять нужно каждое из составляющих имени по-отдельности
во-первых, потому что при такой реализации строки лишние создаются, что всегда не хорошо
во-вторых, потому что мы не должны основываться на знании о том, как устроен метод getFullNameString в другом классе

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +            for (int i = 0; i < length; i++) {
границы указаны неверно

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length - 1; i++) {
границы указаны неверно

2023-12-11 09:43 UTC, safgbad commented on src/EmployeeBook.java
> +                int newSalary = employee.getSalary() * percent / 100;
обычно проценты указываются без учета того, что уже есть
то есть если нужно поднять на 11 процентов, то и указывается 11, а не 111
то есть формулу лучше поменять

2023-12-11 10:22 UTC, EugeneParallax commented on src/EmployeeBook.java
> +                int newSalary = employee.getSalary() * percent / 100;
выбрал такое решение, потому что в условии указано "изменить" зарплаты, а не "поднять", т. е. возможно и понижение, поэтому можно ввести число меньше 100 (например 95%), и код сработает. Может быть я не знаю правильного значения индексации, так что поменяю, раз рекомендуете.

2023-12-11 10:27 UTC, EugeneParallax commented on src/EmployeeBook.java
> +        String keyword = lastName + ' ' + firstName + ' ' + patronymic;
поменяю. Исходил из того что иначе потребуется строить пирамиды операторов if, что не очень читабельно. Посчитал что создание одной новой строчки для обхода этой проблемы будет допустимо. Кстати, вопрос если уж решили посмотреть - вывод в консоль также создает строчку в пуле, прежде чем он сможет ее распечатать? Или это как-то реализуется без пула?

2023-12-11 10:30 UTC, safgbad commented on src/EmployeeBook.java
> +                int newSalary = employee.getSalary() * percent / 100;
при понижении можно просто передать отрицательное значение, с этим не должно быть проблем

2023-12-11 10:33 UTC, EugeneParallax commented on src/Employee.java
> +        employee.branch = (byte) branch;
реализую второй вариант. Я так понимаю что переопределение переменных на типы более низкого разрешения делают в исключительных случаях, когда это спасает производительность.

2023-12-11 10:34 UTC, EugeneParallax commented on src/Employee.java
> +        employee.employeeID = employeeIDCounter;
перепишу. Просто это вроде был формат конструктора предложенный в уроках по классам.

2023-12-11 10:44 UTC, safgbad commented on src/EmployeeBook.java
> +        String keyword = lastName + ' ' + firstName + ' ' + patronymic;
оператор if может быть один с составным условием (используя &&)

по поводу строк – дело не только в пуле
в пул не добавляются те строки, которые образованы конкатенацией (через +)
однако в памяти за пределами пула они всё равно будут существовать и занимать место
вывод в консоль не подразумевает каких-то особых правил. допустим при выводе в консоль
```java
System.out.println("one" + "two");
```
в пуле окажутся строки "one" и "two", а за пределами пула останется строка "onetwo"

2023-12-11 10:49 UTC, safgbad commented on src/Employee.java
> +        employee.branch = (byte) branch;
не смогу придумать пример, когда приводят к типу меньшей размерности)
просто если пришел int 200, то при переводе в byte там уже не будет 200, а будет что-то другое
можно сильно напортачить таким образом

2023-12-11 10:50 UTC, safgbad commented on src/Employee.java
> +        employee.employeeID = employeeIDCounter;
в материалах после этого формата идет раздел "Модифицируем наш метод в «конструктор»"

2023-12-11 13:02 UTC, EugeneParallax commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
Да, че-то затупил с этим. Там же < везде. Без отсылки на i в теле, можно применять foreach даже. Поправлю.

2023-12-11 13:09 UTC, EugeneParallax commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
Я уже слышал про перегрузку, но пока на практике не знаю как это применять. В домашках вроде еще не попадалось нужда это делать. Буду благодарен за пояснение. Это нужно добавлить как отдельный метод в класс, чтобы он понимал вызов метода без аргументов и перенаправлял его на имеющийся метод с нужным аргументом? Вроде помню что методы с одинаковым ярлыком но разными аргументами или их порядком считаются разными методами.

2023-12-11 14:03 UTC, EugeneParallax commented on src/EmployeeBook.java
> +        String keyword = lastName + ' ' + firstName + ' ' + patronymic;
Понял. Сделаю лесенкой пока, чтобы не делать супер-длунную строчку кода.

А в чем отличие пула и "запулья"? Пул хранит только те строчки на которые есть действующие ссылки из объектов? А память вне пула очищается только при завершении пробега исполняемого кода?

2023-12-11 15:49 UTC, safgbad commented on src/EmployeeBook.java
> +        String keyword = lastName + ' ' + firstName + ' ' + patronymic;
лесенкой нормально будет, да

нет, чисткой памяти занимается Garbage Collector и он тут не при чем (это справедливо для версий Java 7+)
я предлагаю тебе ознакомиться со статьей: https://topjava.ru/blog/rukovodstvo-po-string-pool-v-java
я в любом случае лучше чем там не смогу объяснить)
если вкратце, то если строка создается уже после компиляции (например, когда строка образуется путем слияния нескольких строк, указанными переменными), то она не помещается в пул

также рекомендую "поиграться" немного с оператором ==, который сравнивает ссылки
```java
String str1 = "tic";
String str2 = "tac";
String str3 = str1 + str2;
String str4 = "tictac";
System.out.println(str3 == str4);
```
в этом примере будет выведено false, так как значение str3 было вычислено уже после компиляции следовательно, str3 не будет в пуле, а str4 – будет

```java
String str1 = "tic" + "tac";
String str2 = "tictac";
System.out.println(str1 == str2);
```
а здесь уже будет true, потому что компилятор преобразовал это к следующему коду:
```java
String str1 = "tictac";
String str2 = "tictac";
System.out.println(str1 == str2);
```
преобразованный код можно найти в папке out

2023-12-11 15:54 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
> Это нужно добавлить как отдельный метод в класс, чтобы он понимал вызов метода без аргументов и перенаправлял его на имеющийся метод с нужным аргументом?

да, всё верно
перегрузка позволяет в пределах одного класса объявить методы с одинаковым названием, но с разными аргументами
https://sky.pro/media/chto-takoe-peregruzka-metodov-v-java/

2023-12-11 15:55 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 0; i < this.employeeList.length - 1; i++) {
напиши, пожалуйста, на платформу скайпро как готов будешь)
с гитхаба уведомления не всегда доходят

2023-12-12 05:37 UTC, safgbad requested changes

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        int salaryMinEmployee = -1;
нужно проверку в конце метода на -1
иначе если сотрудников в отделе нет, то будет ошибка ArrayOutOfBoundsException при вызове элемента массива с индексом -1

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        int salaryMaxEmployee = -1;
в этом методе в конце также нужно проверку на -1 сделать

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length; i++) {
начальное значение i должно быть 0

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length; i++) {
здесь также i нужно инициализировать нулем

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length; i++) {
здесь тоже 0

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length; i++) {
и здесь тоже

2023-12-12 05:37 UTC, safgbad commented on src/EmployeeBook.java
> +        for (int i = 1; i < this.employeeList.length; i++) {
и здесь)

2023-12-12 13:36 UTC, merged